### PR TITLE
fix: Collect data on incomplete frames

### PR DESCRIPTION
**Pull request by ppodolsky**

### CODE REVIEW

**Comment by rklaehn** [comment]
Can you post an example of the error that is fixed by this?

I think if it frequently happens that a message is split over multiple frames despite the frame size being very large, we should just add a length prefix for framing instead of repeatedly deserializing.

**Comment by rklaehn** [comment]
Can you post an example of the error that is fixed by this?

I think if it frequently happens that a message is split over multiple frames despite the frame size being very large, we should just add a length prefix for framing instead of repeatedly deserializing.

**Comment by ppodolsky** [comment]
> Can you post an example of the error that is fixed by this?
> 
> I think if it frequently happens that a message is split over multiple frames despite the frame size being very large, we should just add a length prefix for framing instead of repeatedly deserializing.

Err(RecvError(A(DeserializeError(Io(Custom { kind: UnexpectedEof, error: "" })))

It repeatedly fails on the same block so the error is not random. For some reasons a single BitswapResponse with 1MB block splits into two frames. Don't remeber exact sizes but this was something like ~1040000 + very small tail (1 or 48 bytes).
I may give CID for the block but not sure it is resolvable from the wild web.

**Comment by rklaehn** [comment]
Weird. We set the max frame size to 16mb. And I did quite a few tests with larger blocks.

It might be that the best thing to do is to just forget about the whole 1 msg = 1 frame thing and add a framing like is done in the original quinn transport. Too bad.

Are you using the latest version where the frame size is at the maximum (0xFFFFFF)?

https://docs.rs/tokio-util/latest/tokio_util/codec/struct.Framed.html#

**Comment by ppodolsky** [comment]
> I think if it frequently happens that a message is split over multiple frames despite the frame size being very large, we should just add a length prefix for framing instead of repeatedly deserializing.

I resolved about 200 1MB blocks before the first occurence of the error.

Yeah, length-prefix is a solution too if backward-compatibility is not required here.

> Weird. We set the max frame size to 16mb. And I did quite a few tests with larger blocks.
> 
> It might be that the best thing to do is to just forget about the whole 1 msg = 1 frame thing and add a framing like is done in the original quinn transport. Too bad.
> 
> Are you using the latest version where the frame size is at the maximum (0xFFFFFF)?
> 
> https://docs.rs/tokio-util/latest/tokio_util/codec/struct.Framed.html#

Yeah, I'm testing on master of iroh and master of quic-rpc. Seems that framing is not due to frame size, but due to some other events. May be buffer-size for reading somewhere in the middle of pipeline causes clipping of reading or something like that.

**Comment by rklaehn** [comment]
> > I think if it frequently happens that a message is split over multiple frames despite the frame size being very large, we should just add a length prefix for framing instead of repeatedly deserializing.
> 
> I resolved about 200 1MB blocks before the first occurence of the error.
> 
> Yeah, length-prefix is a solution too if backward-compatibility is not required here.
> 
Backwards compat is not required. The RPC will also not attempt to work for services with different iroh versions. We can't afford to spend too much time with backwards compat at this time, otherwise we won't be able to move fast enough.

> > Weird. We set the max frame size to 16mb. And I did quite a few tests with larger blocks.
> > It might be that the best thing to do is to just forget about the whole 1 msg = 1 frame thing and add a framing like is done in the original quinn transport. Too bad.
> > Are you using the latest version where the frame size is at the maximum (0xFFFFFF)?
> > https://docs.rs/tokio-util/latest/tokio_util/codec/struct.Framed.html#
> 
> I'm testing on master of iroh and master of quic-rpc. Seems that framing is not due to frame size, but due to some other events. May be buffer-size for reading somewhere in the middle of pipeline causes clipping of reading or something like that.

OK. I would prefer just using an additional length prefix. If you want you can do it, possibly using the stuff from tokio util. Otherwise I will do it in a few days. Not worth spending too much time on this.

**Comment by ppodolsky** [comment]
Added logs to split events, found the following pattern of splitted frames:

```received incomplete frame: 1 bytes
aggregating frame: 1 bytes with new frame 1048599 bytes```

or

```received incomplete frame: 1048194 bytes
aggregating frame: 1048194 bytes with new frame 406 bytes```

First line is for the first incomplete frame and the second is for the following frame

**Comment by ppodolsky** [comment]
In the case of 1 bytes + remaining bytes we can't use even length-encoded codec. I believe length-prefix takes more than 1 byte. Need to figure out why this split happens.

**Comment by rklaehn** [comment]
You think the length encoding won't deal with stuff arriving as individual bytes? Anyway, if this is reproducible we can just try it out.

**Comment by rklaehn** [comment]
Can you take a look and try out https://github.com/n0-computer/quic-rpc/pull/26 ?

**Comment by ppodolsky** [comment]
Yes, it is working now!
I was trying to create a reproducable example but fetching problem block through a standalone request with iroh-one always succeeded. Seems that this splitting issue occurs only under network/memory pressure.

**Comment by ppodolsky** [comment]
The most I've found in the Internet is thread https://github.com/hyperium/hyper/issues/2293
Still have no idea why a single message may be splitted into two separate IP packets anyway. Probably socket buffers (rmem_max/wmem_max)?

**Comment by rklaehn** [comment]
So #26 is working for you?

For http chunking I really would not have been surprised by the splitting. But I had hoped that for http2 this would not be the case. A http2 frame already has a 3 byte length prefix and all that stuff. But, 🤷‍♂️  .

So you think I should polish #26 a bit and go with that?

**Comment by ppodolsky** [comment]
Yes, iroh-rpc from #26 is working for me. Let's close my PR and move discussion there

**Pull request closed without merging**
